on: 
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: linux-amd64
    steps:
      - uses: actions/checkout@v4
      - run: ls -alh
      # - run: echo "test success"
      - run: echo " ${{ gitea.workspace }}"
      - run: echo " ${{ gitea.repository }}"